// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Configuration() {
  return window['go']['main']['App']['Configuration']();
}

export function Definitions() {
  return window['go']['main']['App']['Definitions']();
}

export function Identity(arg1) {
  return window['go']['main']['App']['Identity'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function UpdateConfiguration(arg1) {
  return window['go']['main']['App']['UpdateConfiguration'](arg1);
}
