// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Configuration():Promise<string>;

export function Definitions():Promise<string>;

export function Identity(arg1:string):Promise<string>;

export function Start(arg1:string):Promise<string>;

export function Status():Promise<string>;

export function Stop():Promise<void>;

export function UpdateConfiguration(arg1:string):Promise<string>;
