// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSubscription(arg1:number):Promise<void>;

export function CatalogJSON(arg1:string):Promise<string>;

export function Close():Promise<void>;

export function Connect():Promise<void>;

export function DeactivateProfile():Promise<void>;

export function DeleteProfile(arg1:string,arg2:string):Promise<void>;

export function DeleteView(arg1:string,arg2:number):Promise<void>;

export function Disconnect():Promise<void>;

export function IdentityJSON():Promise<string>;

export function InvokeJSON(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LoginJSON(arg1:string):Promise<string>;

export function LogsJSON():Promise<string>;

export function OperateJSON(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function PollSubscription(arg1:number,arg2:number):Promise<string>;

export function PrepareProfileJSON(arg1:string):Promise<string>;

export function ProfileStatesJSON():Promise<string>;

export function ResetStorage(arg1:string):Promise<string>;

export function SaveProfileJSON(arg1:string):Promise<string>;

export function SaveViewJSON(arg1:string):Promise<string>;

export function SelectUploadFile():Promise<string>;

export function SettingsJSON():Promise<string>;

export function SnapshotJSON(arg1:string,arg2:string):Promise<string>;

export function StatusJSON():Promise<string>;

export function Subscribe(arg1:string,arg2:string,arg3:number):Promise<number>;

export function SubscribeCapability(arg1:string,arg2:string,arg3:string,arg4:number):Promise<number>;

export function SwitchProfile(arg1:string):Promise<void>;

export function TopologyJSON(arg1:string):Promise<string>;

export function UploadFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ViewsJSON():Promise<string>;

export function WaitConnected(arg1:number):Promise<void>;
