// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSubscription(arg1) {
  return window['go']['main']['App']['CancelSubscription'](arg1);
}

export function CatalogJSON(arg1) {
  return window['go']['main']['App']['CatalogJSON'](arg1);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function FileTransfersJSON(arg1) {
  return window['go']['main']['App']['FileTransfersJSON'](arg1);
}

export function FlowDefinitionsJSON(arg1) {
  return window['go']['main']['App']['FlowDefinitionsJSON'](arg1);
}

export function FlowRunsJSON(arg1) {
  return window['go']['main']['App']['FlowRunsJSON'](arg1);
}

export function GrantPolicyJSON(arg1, arg2) {
  return window['go']['main']['App']['GrantPolicyJSON'](arg1, arg2);
}

export function HealthJSON(arg1) {
  return window['go']['main']['App']['HealthJSON'](arg1);
}

export function IdentityJSON() {
  return window['go']['main']['App']['IdentityJSON']();
}

export function InvokeJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['InvokeJSON'](arg1, arg2, arg3);
}

export function IssuePermitJSON(arg1, arg2) {
  return window['go']['main']['App']['IssuePermitJSON'](arg1, arg2);
}

export function LogsJSON() {
  return window['go']['main']['App']['LogsJSON']();
}

export function ManagementConfigJSON(arg1) {
  return window['go']['main']['App']['ManagementConfigJSON'](arg1);
}

export function PollSubscription(arg1, arg2) {
  return window['go']['main']['App']['PollSubscription'](arg1, arg2);
}

export function ResetStorage(arg1) {
  return window['go']['main']['App']['ResetStorage'](arg1);
}

export function RevokeNodeJSON(arg1, arg2) {
  return window['go']['main']['App']['RevokeNodeJSON'](arg1, arg2);
}

export function RevokePolicyJSON(arg1, arg2) {
  return window['go']['main']['App']['RevokePolicyJSON'](arg1, arg2);
}

export function SaveSettingsJSON(arg1) {
  return window['go']['main']['App']['SaveSettingsJSON'](arg1);
}

export function SettingsJSON() {
  return window['go']['main']['App']['SettingsJSON']();
}

export function SnapshotJSON(arg1, arg2) {
  return window['go']['main']['App']['SnapshotJSON'](arg1, arg2);
}

export function StatusJSON() {
  return window['go']['main']['App']['StatusJSON']();
}

export function Subscribe(arg1, arg2, arg3) {
  return window['go']['main']['App']['Subscribe'](arg1, arg2, arg3);
}

export function TopologyJSON(arg1) {
  return window['go']['main']['App']['TopologyJSON'](arg1);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3, arg4);
}

export function WaitConnected(arg1) {
  return window['go']['main']['App']['WaitConnected'](arg1);
}
