// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSubscription(arg1) {
  return window['go']['main']['App']['CancelSubscription'](arg1);
}

export function CatalogJSON(arg1) {
  return window['go']['main']['App']['CatalogJSON'](arg1);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function DeleteProfile(arg1, arg2) {
  return window['go']['main']['App']['DeleteProfile'](arg1, arg2);
}

export function DeleteView(arg1, arg2) {
  return window['go']['main']['App']['DeleteView'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function IdentityJSON() {
  return window['go']['main']['App']['IdentityJSON']();
}

export function InvokeJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['InvokeJSON'](arg1, arg2, arg3);
}

export function LoginJSON(arg1) {
  return window['go']['main']['App']['LoginJSON'](arg1);
}

export function LogsJSON() {
  return window['go']['main']['App']['LogsJSON']();
}

export function OperateJSON(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OperateJSON'](arg1, arg2, arg3, arg4, arg5);
}

export function PollSubscription(arg1, arg2) {
  return window['go']['main']['App']['PollSubscription'](arg1, arg2);
}

export function PrepareProfileJSON(arg1) {
  return window['go']['main']['App']['PrepareProfileJSON'](arg1);
}

export function ResetStorage(arg1) {
  return window['go']['main']['App']['ResetStorage'](arg1);
}

export function SaveProfileJSON(arg1) {
  return window['go']['main']['App']['SaveProfileJSON'](arg1);
}

export function SaveViewJSON(arg1) {
  return window['go']['main']['App']['SaveViewJSON'](arg1);
}

export function SettingsJSON() {
  return window['go']['main']['App']['SettingsJSON']();
}

export function SnapshotJSON(arg1, arg2) {
  return window['go']['main']['App']['SnapshotJSON'](arg1, arg2);
}

export function StatusJSON() {
  return window['go']['main']['App']['StatusJSON']();
}

export function Subscribe(arg1, arg2, arg3) {
  return window['go']['main']['App']['Subscribe'](arg1, arg2, arg3);
}

export function SubscribeCapability(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubscribeCapability'](arg1, arg2, arg3, arg4);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function TopologyJSON(arg1) {
  return window['go']['main']['App']['TopologyJSON'](arg1);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3, arg4);
}

export function ViewsJSON() {
  return window['go']['main']['App']['ViewsJSON']();
}

export function WaitConnected(arg1) {
  return window['go']['main']['App']['WaitConnected'](arg1);
}
